source :rubygems

gem 'sinatra', '1.3.1'
gem 'service_manager', '0.6.2'
#START_HIGHLIGHT
gem 'activerecord', '3.1.3'
gem 'sqlite3', '1.3.5'
#END_HIGHLIGHT

group :development do
  gem 'rspec', '2.7.0'
  gem 'cucumber', '1.1.3'
  gem 'capybara', '1.1.2'
  gem 'launchy', '2.0.5'
end

