source 'http://rubygems.org'

gem 'rails', '3.1.3'

gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :test do
  gem 'cucumber-rails', '1.2.1'
  gem 'rspec-rails', '2.7.0'
  gem 'database_cleaner', '0.7.0'
end
